---
- name: install Apache and upload simple web page
  hosts: all
  become: yes

  vars:
    source_file: ./for_deploy/index.html
    destin_file: /var/www/html

  tasks:
  - name: Print linux distribution family
    debug: var=ansible_os_family


  - block: # RedHat block   

    - name: Install Apache package on RedHat
      yum: name=httpd state=latest

    - name: Upload web page
      copy: src={{ source_file }} dest={{ destin_file }} mode=055
      notify: Restart Apache service RedHat
   
    - name: Start and enable Apache service on RedHat
      service: name=httpd state=started enabled=yes

    when: ansible_os_family == "RedHat"

  - block: # Debian block

    - name: Install Apache package on Debian
      apt: name=apache2 state=latest

    - name: Upload web page
      copy: src={{ source_file }} dest={{ destin_file }} mode=055
      notify: Restart Apache service Debian

    - name: Start and enable Apache service on Debian
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache service RedHat
    service: name=httpd state=restarted

  - name: Restart Apache service Debian
    service: name=apache2 state=restarted
